name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - run: rustup component add rustfmt
      - name: check rustfmt
        run: cargo fmt -- --check --color always

  windows_stable:
    runs-on: windows-latest
    steps:
      - name: Ninja Install
        uses: crazy-max/ghaction-chocolatey@v1.3.1
        with:
          args: install ninja
      - name: Python3 Install
        uses: crazy-max/ghaction-chocolatey@v1.3.1
        with:
          args: install python3 --params "/InstallAllUsers"
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  linux_stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: sudo apt-get install build-essential git python cmake libvulkan-dev vulkan-utils libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  macos_stable:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
